### ISSUE TITLE
avocado server api test missing job.main() entry point

### ISSUE THREAD

**Issue by lmr** [avocado-framework/avocado-server#18]
diff --git a/selftests/all/functional/avocadoserver/api.py b/selftests/all/functional/avocadoserver/api.py
    index 8f9a74d..c617d01 100644
    --- a/selftests/all/functional/avocadoserver/api.py
    +++ b/selftests/all/functional/avocadoserver/api.py
    @@ -5,6 +5,7 @@ run.
     """
     
     from avocado import test
    +from avocado import job
     
     import json
     import requests
    @@ -260,3 +261,6 @@ class api(test.Test):
             self.test_jobs_add()
             self.test_jobs_del()
             self.test_jobs_activities_empty()
    +
    +if __name__ == '__main__':
    +    job.main()

**Comment by clebergnu** [comment]
Sure thing! Let's add that!

**Comment by lmr** [comment]
Looks good!

**Comment by lmr** [comment]
Issue solved.
