### ISSUE TITLE
How to use this.

### ISSUE THREAD

**Issue by omps** [avocado-framework/avocado-server#56]
How to use the avocado server, couldn't find appropriate documentation?

**Comment by omps** [comment]
http://avocado-server.readthedocs.io/en/latest/Introduction.html

**Comment by ldoktor** [comment]
Btw this is in "alpha" stage so don't expect production-ready environment but contributions are welcome or you can use it as a foundation to your custom app.

**Comment by omps** [comment]
sure. I will be checking and sending pull request if I find anything fixed.
